#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'jekyll-timeago/filter'
include Jekyll::Timeago::Filter

require 'irb'
ARGV.clear
IRB.start
